version: '2'
services:
        web:
                build: ./web/
                expose:
                        - "8000"
                environment:
                        - PYTHONPATH=/app/func_test
                        - DJANGO_SETTINGS_MODULE=functest.settings
                command: gunicorn functest.wsgi -c func_test/functest/gunicorn.conf.py
                volumes:
                        - ./web/func_test/:/app/func_test
                depends_on:
                        - db
                        - rabbit

        celery:
                build: ./web/
                environment:
                        - PYTHONPATH=/app/func_test
                        - DJANGO_SETTINGS_MODULE=functest.settings
                        - BROKER_URL=amqp://rabbit:rabbit@rabbit//
                command: celery -A functest worker -E -l info --concurrency=3
                depends_on:
                        - rabbit
                        - db

        nginx:
                build: ./nginx/
                ports:
                        - "80:80"
                volumes_from:
                        - web
                links:
                        - web:web

        db:
                build: ./postgresql/

        rabbit:
                build: ./rabbitmq/
                environment:
                        RABBITMQ_ERLANG_COOKIE: "some_secret_cookie"
                        RABBITMQ_DEFAULT_USER: "rabbit"
                        RABBITMQ_DEFAULT_PASS: "rabbit"
                        RABBITMQ_DEFAULT_VHOST: "/"
                ports:
                        - "15672:15672"
                        - "5672:5672"
