# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='error',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exception',
        ),
        migrations.AddField(
            model_name='testrun',
            name='error',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='testrun',
            name='exception',
            field=models.TextField(null=True, verbose_name='Error Description'),
        ),
        migrations.AlterField(
            model_name='result',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('INPROGRESS', 'INPROGRESS'), ('DONE', 'DONE'), ('ERROR', 'ERROR')], db_index=True, default='NEW', max_length=40),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('INPROGRESS', 'INPROGRESS'), ('DONE', 'DONE'), ('ERROR', 'ERROR')], db_index=True, default='NEW', max_length=40),
        ),
    ]
